#!/bin/bash
# Simple bash alternative to generate-index.py
# For users who prefer not to use Python/YAML

echo "🔨 Generating index.html with bash..."

# Check if examples/ exists
if [ ! -d "examples" ]; then
    echo "❌ Error: examples/ directory not found!"
    exit 1
fi

# Count dashboards
DASHBOARD_COUNT=$(ls examples/*.html 2>/dev/null | wc -l)

if [ $DASHBOARD_COUNT -eq 0 ]; then
    echo "⚠️  No HTML files found in examples/"
    exit 1
fi

echo "✅ Found $DASHBOARD_COUNT dashboard(s)"

# Generate HTML
cat > index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <title>Ansible Dashboard Gallery</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Red Hat Display', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #2d3748;
            min-height: 100vh;
        }
        .hero {
            background: rgba(0, 0, 0, 0.3);
            color: white;
            padding: 60px 20px;
            text-align: center;
            backdrop-filter: blur(10px);
        }
        .hero h1 {
            font-size: 3em;
            font-weight: 800;
            margin-bottom: 10px;
        }
        .container {
            max-width: 1400px;
            margin: 40px auto;
            padding: 0 20px;
        }
        .dashboard-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
            gap: 25px;
        }
        .dashboard-card {
            background: white;
            border-radius: 10px;
            padding: 25px;
            transition: all 0.3s;
            cursor: pointer;
            border: 2px solid #e2e8f0;
        }
        .dashboard-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            border-color: #3b82f6;
        }
        .dashboard-title {
            font-size: 1.3em;
            font-weight: 600;
            color: #1e3a8a;
            margin-bottom: 10px;
        }
        .dashboard-link {
            color: #3b82f6;
            text-decoration: none;
            font-weight: 600;
        }
        footer {
            background: rgba(0, 0, 0, 0.8);
            color: white;
            text-align: center;
            padding: 30px;
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <div class="hero">
        <h1>🚀 Ansible Dashboard Gallery</h1>
        <p>Production-ready dashboard examples</p>
    </div>
    <div class="container">
        <div class="dashboard-grid">
EOF

# Add dashboard cards
for file in examples/*.html; do
    filename=$(basename "$file")
    title=$(echo "$filename" | sed 's/.html$//' | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

    cat >> index.html << EOF
            <div class="dashboard-card" onclick="window.location.href='examples/$filename'">
                <h3 class="dashboard-title">$title</h3>
                <a href="examples/$filename" class="dashboard-link">View Dashboard →</a>
            </div>
EOF
done

# Close HTML
cat >> index.html << EOF
        </div>
    </div>
    <footer>
        <p><strong>Generated by Ansible Dashboard Gallery</strong></p>
        <p>Last generated: $(date '+%Y-%m-%d %H:%M:%S UTC')</p>
    </footer>
</body>
</html>
EOF

echo "✅ Successfully generated index.html"
echo "📊 Total: $DASHBOARD_COUNT dashboards"
